-- Insert 3 Talent (Actor) profiles using existing user ID
INSERT INTO public.talents (
  id, user_id, name, email, phone, applicant_type, category, bio,
  city, state, country, height, weight, bust, waist, hips, shoe_size,
  hair_color, eye_color, ethnicity, age_range, skin_tone,
  clothing_size_top, clothing_size_bottom,
  has_tattoos, tattoo_notes, has_piercings, piercing_notes, distinguishing_features,
  comfort_speaking, comfort_improv, comfort_romance_level, comfort_stunts, comfort_swimwear,
  has_drivers_license, willing_to_travel, has_passport,
  languages, union_status, skills_tags, availability_notes, availability_dates,
  primary_photo_url, video_reel_url,
  instagram_url, tiktok_url, youtube_url, website_url, imdb_url,
  is_approved, is_active, is_featured, profile_completeness
) VALUES
(
  gen_random_uuid(),
  '2a8d9325-2e56-4478-ab2f-03ec52cb02ad',
  'Maya Johnson',
  'maya.johnson@example.com',
  '+1 (310) 555-0142',
  'talent',
  'actor',
  'Award-winning actress with 8+ years of experience in film, television, and theater. Known for versatile dramatic performances and comedic timing. Featured in multiple streaming series and independent films. Trained at the Lee Strasberg Theatre & Film Institute.',
  'Los Angeles',
  'California',
  'United States',
  '5''7"',
  '135 lbs',
  '34"',
  '26"',
  '36"',
  '8',
  'Black',
  'Brown',
  'African American',
  '25-35',
  'Brown',
  'Medium',
  '6',
  false,
  NULL,
  true,
  'Ear piercings only',
  'Distinctive smile, beauty mark on left cheek',
  true,
  true,
  'pg13',
  true,
  true,
  true,
  true,
  true,
  ARRAY['English', 'Spanish', 'French'],
  'SAG-AFTRA',
  ARRAY['Drama', 'Comedy', 'Action', 'Voice Over', 'Singing', 'Dancing', 'Martial Arts'],
  'Available for projects starting January 2025',
  'January 2025 - March 2025',
  'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/76979871',
  'https://instagram.com/mayajohnson',
  'https://tiktok.com/@mayajohnson',
  'https://youtube.com/@mayajohnsonactor',
  'https://mayajohnson.com',
  'https://imdb.com/name/nm0000001',
  true,
  true,
  true,
  95
),
(
  gen_random_uuid(),
  '48e622a4-b777-49f2-b44a-66c18e3df9fc',
  'Marcus Chen',
  'marcus.chen@example.com',
  '+1 (404) 555-0198',
  'talent',
  'actor',
  'Classically trained actor specializing in dramatic roles. Graduate of Yale School of Drama with extensive stage experience. Recently transitioned to screen work with recurring roles on network television. Passionate about authentic storytelling and complex characters.',
  'Atlanta',
  'Georgia',
  'United States',
  '6''1"',
  '180 lbs',
  '42"',
  '32"',
  '38"',
  '11',
  'Black',
  'Dark Brown',
  'Asian American',
  '30-40',
  'Medium',
  'Large',
  '32',
  false,
  NULL,
  false,
  NULL,
  'Scar on right forearm from stunt work',
  true,
  true,
  'mature',
  true,
  true,
  true,
  true,
  true,
  ARRAY['English', 'Mandarin', 'Cantonese'],
  'SAG-AFTRA',
  ARRAY['Drama', 'Thriller', 'Stage Combat', 'Martial Arts', 'Weapons Training', 'Horseback Riding'],
  'Currently filming until December, then fully available',
  'January 2025 onwards',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/148751763',
  'https://instagram.com/marcuschenactor',
  NULL,
  'https://youtube.com/@marcuschen',
  'https://marcuschen.actor',
  'https://imdb.com/name/nm0000002',
  true,
  true,
  false,
  92
),
(
  gen_random_uuid(),
  '05520256-76d3-419c-b42f-2fae435603d0',
  'Sofia Rodriguez',
  'sofia.rodriguez@example.com',
  '+1 (212) 555-0167',
  'talent',
  'actor',
  'Bilingual actress and model with experience in commercials, music videos, and independent films. Known for energetic personality and natural screen presence. Strong dance background including ballet, hip-hop, and contemporary. Seeking lead and supporting roles in comedy and drama.',
  'New York',
  'New York',
  'United States',
  '5''9"',
  '140 lbs',
  '34"',
  '25"',
  '35"',
  '9',
  'Brown',
  'Hazel',
  'Hispanic/Latina',
  '22-30',
  'Olive',
  'Small',
  '4',
  true,
  'Small flower tattoo on ankle',
  true,
  'Multiple ear piercings, nose stud',
  'Freckles across nose and cheeks',
  true,
  true,
  'pg13',
  false,
  true,
  true,
  true,
  true,
  ARRAY['English', 'Spanish', 'Portuguese'],
  'Non-union',
  ARRAY['Comedy', 'Romance', 'Dancing', 'Singing', 'Modeling', 'Hosting', 'Improvisation'],
  'Flexible schedule, can travel on short notice',
  'Available immediately',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/315849498',
  'https://instagram.com/sofiarodrigueznyc',
  'https://tiktok.com/@sofiarod',
  NULL,
  'https://sofiarodriguez.co',
  NULL,
  true,
  true,
  true,
  88
);

-- Insert 3 Crew profiles
INSERT INTO public.talents (
  id, user_id, name, email, phone, applicant_type, category, bio,
  city, state, country,
  willing_to_travel, has_passport, has_drivers_license,
  languages, availability_notes, availability_dates,
  crew_primary_role, crew_secondary_roles, crew_years_experience,
  crew_gear_owned, crew_software, crew_certifications, crew_work_preferences,
  primary_photo_url, video_reel_url, portfolio_url,
  instagram_url, website_url, imdb_url,
  is_approved, is_active, is_featured, profile_completeness
) VALUES
(
  gen_random_uuid(),
  '796eea51-8bd4-45a0-b47b-6db8fbd13bc7',
  'James Mitchell',
  'james.mitchell@example.com',
  '+1 (323) 555-0234',
  'crew',
  'other',
  'Emmy-nominated Director of Photography with 15+ years of experience in narrative film, documentaries, and commercials. Expertise in both digital (RED, ARRI) and film formats. Known for creating stunning visual narratives with natural lighting. Credits include Netflix originals and Sundance selections.',
  'Los Angeles',
  'California',
  'United States',
  true,
  true,
  true,
  ARRAY['English', 'French'],
  'Currently booking Q1 2025 projects',
  'February 2025 onwards',
  'Director of Photography',
  ARRAY['Camera Operator', 'Gaffer', 'Colorist'],
  15,
  'RED Komodo, ARRI Alexa Mini, Full Zeiss lens kit, Teradek wireless, DJI Ronin 2, Full grip & electric package',
  ARRAY['DaVinci Resolve', 'Premiere Pro', 'Lightroom', 'Frame.io'],
  'ASC Associate Member, Local 600 DP',
  ARRAY['Day', 'Night', 'Weekends', 'Travel'],
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/259411563',
  'https://jamesmitchellcinema.com/portfolio',
  'https://instagram.com/jamesmitchell_dp',
  'https://jamesmitchellcinema.com',
  'https://imdb.com/name/nm0000004',
  true,
  true,
  true,
  98
),
(
  gen_random_uuid(),
  'c3aafcca-d754-4f8a-b303-0033531e69d1',
  'Amanda Park',
  'amanda.park@example.com',
  '+1 (818) 555-0321',
  'crew',
  'other',
  'Creative and detail-oriented Production Designer with a decade of experience in film and television. Specializing in period pieces and sci-fi productions. Strong background in architecture and fine arts. Built and managed art departments for major studio productions and streaming platforms.',
  'Burbank',
  'California',
  'United States',
  true,
  true,
  true,
  ARRAY['English', 'Korean'],
  'Available after current project wraps in January',
  'January 2025 - June 2025',
  'Production Designer',
  ARRAY['Art Director', 'Set Decorator', 'Prop Master'],
  10,
  'Full drafting kit, 3D printer, scale model supplies, reference library',
  ARRAY['AutoCAD', 'SketchUp', 'Vectorworks', 'Photoshop', 'Illustrator', 'Cinema 4D'],
  'ADG Local 800 Member, BAFTA Member',
  ARRAY['Day', 'Weekends'],
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/271443456',
  'https://amandaparkdesign.com/work',
  'https://instagram.com/amandapark_design',
  'https://amandaparkdesign.com',
  'https://imdb.com/name/nm0000005',
  true,
  true,
  false,
  94
),
(
  gen_random_uuid(),
  '2a8d9325-2e56-4478-ab2f-03ec52cb02ad',
  'Derek Washington',
  'derek.washington@example.com',
  '+1 (470) 555-0456',
  'crew',
  'other',
  'Award-winning Sound Mixer and Audio Engineer with expertise in production sound for film, television, and live events. Known for clean dialogue recording even in challenging locations. Experience ranges from intimate indie dramas to large-scale action productions. Also provides post-production sound design and mixing services.',
  'Atlanta',
  'Georgia',
  'United States',
  true,
  true,
  true,
  ARRAY['English'],
  'Booking now for spring productions',
  'March 2025 onwards',
  'Sound Mixer',
  ARRAY['Boom Operator', 'Sound Designer', 'Re-Recording Mixer', 'Foley Artist'],
  12,
  'Sound Devices 688, Lectrosonics wireless (8 channels), Schoeps & Sennheiser mics, Ambient boom poles, full backup kit',
  ARRAY['Pro Tools', 'Logic Pro', 'Izotope RX', 'Nuendo', 'Source Connect'],
  'CAS Member, Local 695',
  ARRAY['Day', 'Night', 'Weekends', 'Travel'],
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
  'https://player.vimeo.com/video/318514917',
  'https://derekwashingtonsound.com/reel',
  'https://instagram.com/derekwashington_sound',
  'https://derekwashingtonsound.com',
  'https://imdb.com/name/nm0000006',
  true,
  true,
  false,
  96
);