-- Insert additional movie categories with unique slugs
INSERT INTO categories (name, slug, description, content_type) VALUES
-- Standard Genres (using movie- prefix to ensure uniqueness)
('Adventure', 'adventure-movies', 'Epic journeys and exploration stories', 'movie'),
('Animation', 'animation-movies', 'Animated feature films', 'movie'),
('Biography', 'biography-movies', 'True stories about real people', 'movie'),
('Cartoons', 'cartoons-movies', 'Animated cartoon content for all ages', 'movie'),
('Crime', 'crime-movies', 'Criminal underworld and detective stories', 'movie'),
('Documentary', 'documentary-movies', 'Non-fiction films exploring real subjects', 'movie'),
('Fantasy', 'fantasy-movies', 'Magical worlds and mythical creatures', 'movie'),
('Film Noir', 'film-noir-movies', 'Classic dark crime dramas', 'movie'),
('History', 'history-movies', 'Historical events and period pieces', 'movie'),
('Horror', 'horror-movies', 'Scary and suspenseful films', 'movie'),
('Martial Arts', 'martial-arts-movies', 'Kung fu and martial arts action', 'movie'),
('Musical', 'musical-movies', 'Song and dance performances', 'movie'),
('Mystery', 'mystery-movies', 'Puzzling whodunits and suspenseful plots', 'movie'),
('Romance', 'romance-movies', 'Love stories and romantic tales', 'movie'),
('Sci-Fi', 'sci-fi-movies', 'Science fiction and futuristic stories', 'movie'),
('Short Film', 'short-film-movies', 'Brief cinematic experiences', 'movie'),
('Sports', 'sports-movies', 'Athletic competitions and sports dramas', 'movie'),
('Superhero', 'superhero-movies', 'Comic book heroes and superpowers', 'movie'),
('Thriller', 'thriller-movies', 'Edge-of-your-seat suspense', 'movie'),
('War', 'war-movies', 'Military conflicts and war stories', 'movie'),
('Western', 'western-movies', 'Wild West adventures and cowboys', 'movie'),
-- Regional/Cultural
('Bollywood', 'bollywood-movies', 'Indian cinema from Mumbai', 'movie'),
('British Films', 'british-movies', 'Films from the United Kingdom', 'movie'),
('Caribbean Films', 'caribbean-movies', 'Films from the Caribbean region', 'movie'),
('French Films', 'french-movies', 'Cinema from France', 'movie'),
('Korean Films', 'korean-movies', 'K-cinema from South Korea', 'movie'),
('Latin Films', 'latin-movies', 'Films from Latin America', 'movie'),
('Nigerian Films', 'nigerian-movies', 'Nollywood and Nigerian cinema', 'movie'),
-- Special Categories
('Award Winners', 'award-winners-movies', 'Oscar and award-winning films', 'movie'),
('Classic Films', 'classic-movies', 'Timeless cinema classics', 'movie'),
('Cult Classics', 'cult-classics-movies', 'Films with devoted followings', 'movie'),
('Faith & Spirituality', 'faith-spirituality-movies', 'Inspirational and religious films', 'movie'),
('Independent Films', 'indie-movies', 'Indie and arthouse cinema', 'movie'),
('LGBTQ+', 'lgbtq-movies', 'LGBTQ+ stories and representation', 'movie'),
('Made for TV', 'made-for-tv-movies', 'Television movie productions', 'movie'),
('New Releases', 'new-releases-movies', 'Recently released films', 'movie'),
('Stand-Up Comedy', 'standup-comedy-movies', 'Comedy specials and performances', 'movie'),
('True Crime', 'true-crime-movies', 'Real crime stories and investigations', 'movie'),
('Urban', 'urban-movies', 'Urban lifestyle and street culture films', 'movie');