-- Insert predefined tags (using ON CONFLICT to avoid duplicates)
INSERT INTO public.tags (name, slug, content_type)
VALUES 
  ('MadFaceTV', 'madfacetv', null),
  ('Live From Da Street', 'live-from-da-street', null),
  ('Music Videos', 'music-videos', null),
  ('Hip Hop Videos', 'hip-hop-videos', null),
  ('Kompa', 'kompa', null),
  ('Kompa Videos', 'kompa-videos', null),
  ('Christian Hip Hop', 'christian-hip-hop', null),
  ('Gospel Rap', 'gospel-rap', null),
  ('Reggae Music', 'reggae-music', null),
  ('Reggae Videos', 'reggae-videos', null),
  ('Afro Beats', 'afro-beats', null),
  ('Afro Beat Videos', 'afro-beat-videos', null),
  ('Haitian Music Videos', 'haitian-music-videos', null),
  ('Cooking', 'cooking', null),
  ('Reality Show', 'reality-show', null),
  ('Comedy', 'comedy', null),
  ('Drama', 'drama', null),
  ('Suspense', 'suspense', null),
  ('Horror', 'horror', null),
  ('Romance', 'romance', null),
  ('Documentary', 'documentary', null),
  ('Dating', 'dating', null),
  ('African Movies', 'african-movies', null),
  ('Haitian Movies', 'haitian-movies', null),
  ('Jamaican Movies', 'jamaican-movies', null),
  ('Business', 'business', null),
  ('Educational', 'educational', null),
  ('Crypto', 'crypto', null),
  ('Forex', 'forex', null),
  ('Trading', 'trading', null),
  ('Boss Mogul TV', 'boss-mogul-tv', null),
  ('MyPureTV', 'mypuretv', null),
  ('Zoe RatedTV', 'zoe-ratedtv', null),
  ('AyiTV', 'ayitv', null),
  ('Yard MonTV', 'yard-montv', null)
ON CONFLICT (slug) DO NOTHING;