
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as GeneratedDatabase } from './types';

const SUPABASE_URL = "https://hbddjtvslojxkkcrpcoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZGRqdHZzbG9qeGtrY3JwY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjUxNjcsImV4cCI6MjA2MjYwMTE2N30.TC4eACBOJsfggnuB3OyOK7x4O9yp7bjzOP5Tr9_jHds";

// Extend the generated Database type with our custom tables
interface Database extends GeneratedDatabase {
  public: {
    Tables: {
      profiles: {
        Row: DbProfile;
        Insert: Omit<DbProfile, 'created_at'>;
        Update: Partial<Omit<DbProfile, 'id' | 'created_at'>>;
      };
      contents: {
        Row: DbContent;
        Insert: Omit<DbContent, 'id' | 'created_at'>;
        Update: Partial<Omit<DbContent, 'id' | 'created_at'>>;
      };
      seasons: {
        Row: DbSeason;
        Insert: Omit<DbSeason, 'id' | 'created_at'>;
        Update: Partial<Omit<DbSeason, 'id' | 'created_at'>>;
      };
      episodes: {
        Row: DbEpisode;
        Insert: Omit<DbEpisode, 'id' | 'created_at'>;
        Update: Partial<Omit<DbEpisode, 'id' | 'created_at'>>;
      };
      categories: {
        Row: DbCategory;
        Insert: Omit<DbCategory, 'id' | 'created_at'>;
        Update: Partial<Omit<DbCategory, 'id' | 'created_at'>>;
      };
      tags: {
        Row: DbTag;
        Insert: Omit<DbTag, 'id' | 'created_at'>;
        Update: Partial<Omit<DbTag, 'id' | 'created_at'>>;
      };
      content_tags: {
        Row: DbContentTag;
        Insert: Omit<DbContentTag, 'id' | 'created_at'>;
        Update: Partial<Omit<DbContentTag, 'id' | 'created_at'>>;
      };
      playlists: {
        Row: DbPlaylist;
        Insert: Omit<DbPlaylist, 'id' | 'created_at'>;
        Update: Partial<Omit<DbPlaylist, 'id' | 'created_at'>>;
      };
      playlist_items: {
        Row: DbPlaylistItem;
        Insert: Omit<DbPlaylistItem, 'id' | 'created_at'>;
        Update: Partial<Omit<DbPlaylistItem, 'id' | 'created_at'>>;
      };
    } & GeneratedDatabase['public']['Tables'];
    Views: GeneratedDatabase['public']['Views'];
    Functions: GeneratedDatabase['public']['Functions'];
    Enums: GeneratedDatabase['public']['Enums'];
    CompositeTypes: GeneratedDatabase['public']['CompositeTypes'];
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define our custom types that match the database schema
export type DbProfile = {
  id: string;
  full_name: string | null;
  avatar_url: string | null;
  subscription_tier: string | null;
  created_at: string;
  is_admin?: boolean;
}

export type ContentType = 'movie' | 'show';

export type DbContent = {
  id: string;
  title: string;
  description: string | null;
  type: ContentType;
  genre: string | null;
  release_year: number | null;
  rating: string | null;
  duration: string | null;
  poster_url: string | null;
  backdrop_url: string | null;
  video_url: string | null;
  trailer_url: string | null;
  featured: boolean | null;
  created_at: string;
  vast_ad_preroll: string | null;
  vast_ad_midroll: string | null;
  vast_ad_postroll: string | null;
  category_id?: string | null;
}

export type DbSeason = {
  id: string;
  content_id: string;
  season_number: number;
  title: string | null;
  description: string | null;
  poster_url: string | null;
  created_at: string;
}

export type DbEpisode = {
  id: string;
  season_id: string;
  episode_number: number;
  title: string;
  description: string | null;
  duration: string | null;
  thumbnail_url: string | null;
  video_url: string | null;
  vast_ad_url: string | null;
  created_at: string;
}

export type DbCategory = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  content_type: ContentType;
  created_at: string;
}

export type DbTag = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  content_type: ContentType | null;
  created_at: string;
}

export type DbContentTag = {
  id: string;
  content_id: string;
  tag_id: string;
  created_at: string;
}

export type DbPlaylist = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  content_type: ContentType;
  created_at: string;
}

export type DbPlaylistItem = {
  id: string;
  playlist_id: string;
  content_id: string;
  sort_order: number;
  created_at: string;
}
